# startup cmd
# mysql> GRANT ALL PRIVILEGES ON *.* TO 'ffaFingerprints'@'%' IDENTIFIED BY 'fp1298';
# mysql> flush privileges;
#
# login
# docker-compose exec db 
# mysql --host pmo.ffaprivatebank.com --port 3306 --user=ffaFingerprints --password=fp1298

version: '2'
services:
  db:
    image: mysql:8
    env_file: .env
    environment:
    - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
    - "3306:3306"
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d/

  nats:
    # https://hub.docker.com/_/nats/
    image: nats
    ports:
    - 4222:4222
    - 8222:8222
    - 6222:6222

  updater:
    build:
      context: updater
      dockerfile: Dockerfile
    volumes:
    - /mnt/fingerprints/Program Files/ZKTeco/:/data/ZKTeco
    depends_on:
    - db
    - nats
    links:
    - nats
    env_file: .env

  copier:
    build:
      context: copier
      dockerfile: Dockerfile
    depends_on:
    - db
    - updater
    env_file: .env
    environment:
    - COPIER_TO_1_PASSWORD=$COPIER_TO_1_PASSWORD
    - COPIER_TO_2_PASSWORD=$COPIER_TO_2_PASSWORD
    - COPIER_TO_3_PASSWORD=$COPIER_TO_3_PASSWORD
    - COPIER_TO_4_PASSWORD=$COPIER_TO_4_PASSWORD
    volumes:
    - ./etc:/data/odbc # will copy odbc.ini and odbcinst.ini

