version: '2'
services:
  db:
    image: mysql:8
    environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw
    # variables below are also set in updater/Dockerfile
    - MYSQL_DATABASE=ffa_price_farm
    - MYSQL_USER=ffaFingerprints
    - MYSQL_PASSWORD=fp1298
    ports:
    - "3306:3306"
    volumes:
    - ./updater/initdb:/docker-entrypoint-initdb.d/

  updater:
    build:
      context: updater
      dockerfile: Dockerfile
    volumes:
    - /mnt/fingerprints/Program Files/ZKTeco/:/data/ZKTeco
    depends_on:
    - db

# startup cmd
# mysql> GRANT ALL PRIVILEGES ON *.* TO 'ffaFingerprints'@'%' IDENTIFIED BY 'fp1298';
# mysql> flush privileges;
#
# login
# docker-compose exec db 
# mysql --host pmo.ffaprivatebank.com --port 3306 --user=ffaFingerprints --password=fp1298

