# startup cmd
# mysql> GRANT ALL PRIVILEGES ON *.* TO 'ffaFingerprints'@'%' IDENTIFIED BY 'fp1298';
# mysql> flush privileges;
#
# login
# docker-compose exec db 
# mysql --host pmo.ffaprivatebank.com --port 3306 --user=ffaFingerprints --password=fp1298

version: '2'
services:
  db:
    image: mysql:8
    env_file: .env
    environment:
    - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
    - "3306:3306"
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d/

  nats:
    # https://hub.docker.com/_/nats/
    image: nats
    #ports:
    #- 4222:4222
    #- 8222:8222
    #- 6222:6222

  updater:
    build:
      context: updater
      dockerfile: Dockerfile
    volumes:
    # - /mnt/fingerprints/Program Files/ZKTeco/:/data/ZKTeco
    - /mnt/minerva-laptop/ZKTeco/ZKAccess3.5:/data/ZKTeco
    depends_on:
    - db
    - nats
    links:
    - nats
    env_file: .env
    environment:
    - MYSQL_PASSWORD=$MYSQL_PASSWORD

  copier:
    build:
      context: copier
      dockerfile: Dockerfile
    depends_on:
    - db
    - nats
    env_file: .env
    environment:
    - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
    # will copy odbc.ini and odbcinst.ini, as well as apache2 config
    - /etc/ffa-zkteco-mfbf-copier-odbc:/etc/ffa-zkteco-mfbf-copier-odbc
    volumes_from:
    - updater:ro
    # no need to expose port since redirected internally in service "ui"
    #ports:
    #- "8082:80"

  ui:
    image: nginx:alpine
    depends_on:
    - copier
    volumes:
    - ./ui/www:/usr/share/nginx/html
    - ./ui/etc/:/etc/nginx/conf.d/
    ports:
    - "8083:80"
