# startup cmd
# mysql> GRANT ALL PRIVILEGES ON *.* TO 'ffaFingerprints'@'%' IDENTIFIED BY 'fp1298';
# mysql> flush privileges;
#
# login
# docker-compose exec db 
# mysql --host pmo.ffaprivatebank.com --port 3306 --user=ffaFingerprints --password=fp1298

version: '2'
services:
  db:
    image: mysql:8
    env_file: .env
    ports:
    - "3306:3306"
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d/

  nats:
    # https://hub.docker.com/_/nats/
    image: nats
    ports:
    - 4222:4222
    - 8222:8222
    - 6222:6222

#  updater:
#    build:
#      context: updater
#      dockerfile: Dockerfile
#    volumes:
#    - /mnt/fingerprints/Program Files/ZKTeco/:/data/ZKTeco
#    depends_on:
#    - db
#    - nats
#    links:
#    - nats
#    env_file: .env

#  processor:
#    build:
#      context: processor
#      dockerfile: Dockerfile
#    depends_on:
#    - db
#    - updater
#    volumes:
#    - /etc:/data/odbc # will copy odbc.ini and odbcinst.ini

#  copier:
#    image: shadi/odbc-copier
#    environment:
#    - COPIER_FROM_HOST=db
#    - COPIER_FROM_PORT=3306
#    - COPIER_FROM_DATBASE=ffa_price_farm
#    - COPIER_FROM_USER=ffaFingerprints
#    - COPIER_FROM_PASSWORD=fp1298
#
#    - COPIER_TO_ODBC=MarketflowAcc
#    - COPIER_TO_DATBASE=ffa_price_farm
#    - COPIER_TO_USER=ffaFingerprints
#    - COPIER_TO_PASSWORD=fp1298
#
